In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [2]:
# nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree')

In [3]:
data = pd.read_csv('./very_all_points.csv')
data.drop(['Unnamed: 0'], axis=1)

,id,0,1,2,3,4,5,6,7,8,...,1019,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier
0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,-0.799514,-0.240576,...,0.331789,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False
1,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,0.797688,0.506043,...,-0.320049,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False
2,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,0.699363,-0.028185,...,0.658584,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False
3,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,0.854471,-0.250788,...,0.918464,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False
4,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,-0.918574,0.009565,...,-0.568760,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104359,34781,-0.940447,-0.899166,-0.569543,0.123652,0.985020,-0.617012,0.645699,-0.639426,0.330170,...,-0.496512,-0.986573,-0.284362,0.800393,-0.736587,1.000000e+00,1.982053e-27,0,True,False
104360,266,-0.688172,-0.859654,-0.511220,0.020572,0.999849,-0.131492,0.997604,-0.700331,-0.510287,...,-0.173955,-0.948369,0.888818,-0.629098,-0.971198,1.000000e+00,1.320064e-28,0,True,False
104361,24627,-0.814291,0.782488,-0.735720,-0.144556,0.999998,-0.180351,0.020851,-0.949530,-0.104716,...,0.267554,-0.818821,0.714584,-0.810615,-0.679921,8.074531e-06,9.999919e-01,1,True,False
104362,18084,0.236926,-0.442427,-0.966645,0.139687,0.999998,-0.368226,-0.881570,-0.743715,-0.595993,...,0.998870,0.663736,-0.724384,0.928735,-0.758111,1.000000e+00,6.749659e-16,0,True,False
104363,6879,0.491427,-0.866658,-0.661957,0.016605,0.988620,0.601567,-0.938614,0.929808,0.021855,...,-0.374972,-0.393736,0.956509,-0.227563,-0.541957,1.000000e+00,2.930369e-19,0,True,False

In [4]:
data['nearest_neigbour'] = [None]*len(data)

In [5]:
data.head()

,Unnamed: 0,id,0,1,2,3,4,5,6,7,...,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest_neigbour
0,0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,-0.799514,...,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,None
1,0,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,0.797688,...,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,None
2,0,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,0.699363,...,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,None
3,0,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,0.854471,...,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,None
4,0,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,-0.918574,...,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,None

In [6]:
# data_cls_1 = data.loc[data['class'] == 1]
# data_cls_0 = data.loc[data['class'] == 0]
# data_tab = [data_cls_1, data_cls_0]

In [7]:
# for i in range(len(data)):
#     class_i = data['class'][i]
#     id_i = data['id'][i]
#     print(len(data_tab))
#     X = pd.concat([data[i], data_tab[class_i]]).iloc[:,2:1026].to_numpy()
#     # X = data_tab[class_i].append(data[i]).iloc[:,2:1026].to_numpy()
#     nbrs = nbrs.fit(X)
#     distances, indices = nbrs.kneighbors(X)
#     prov_data = data.loc[data['class'] != some_value]
#     X = data.iloc[:,2:1026].to_numpy()
#     data['nearest_neigbour'][i] = data['id'][neibourg_id]

In [8]:
# nbrs = nbrs.fit(X)

In [9]:
# distances, indices = nbrs.kneighbors(X)

In [10]:
# data.head()

In [11]:
from numpy import random
from scipy.spatial import distance

def closest_node(node, nodes):
    closest_index = distance.cdist([node.to_numpy()], nodes.to_numpy(), 'euclidean').argmin()
    return closest_index #, nodes[closest_index]

In [12]:
a_class_1 = data[(data['class']!=1) & (data['good_predict'])].iloc[:, 2:1026] # data[(data['class']!=1) & (data['good_predict'])]
a_class_0 = data[(data['class']!=0) & (data['good_predict'])].iloc[:, 2:1026]

for i in data.index:
    class_i = data['class'][i]
#     print('la_class : '+str(class_i))
    id_i = data['id'][i]
#     print('la_id : '+str(id_i))
#     a = data[data['class']!=class_i and data['good_predict']].iloc[lambda x: x.index != i, 2:1026]
#     print('len(cible) : '+str(len(a)))
    #some_pt = (1, 2)
#     print(data.iloc[i, 2:1026])
#     print(a)
    if class_i == 0:
        closest_index = closest_node(data.iloc[i, 2:1026], a_class_0)
        index = a_class_0.iloc[closest_index].name
    else :
        closest_index = closest_node(data.iloc[i, 2:1026], a_class_1)
        index = a_class_1.iloc[closest_index].name
#     print(closest_index)
    
#     print(closest_index, closest_value)
#     print('class id and cible '+str(data[data.index == index]['id'])+" "+str(data[data.index == index]['class']))
    if i%4000==0:
        print(str(i)+"/"+str(len(data)))
    data['nearest_neigbour'][i] = data[data.index == index]['id'].values[0] #[index]

0/104364

/home/alexis/.local/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

4000/104364
8000/104364
12000/104364
16000/104364
20000/104364
24000/104364
28000/104364
32000/104364
36000/104364
40000/104364
44000/104364
48000/104364
52000/104364
56000/104364
60000/104364
64000/104364
68000/104364
72000/104364
76000/104364
80000/104364
84000/104364
88000/104364
92000/104364
96000/104364
100000/104364
104000/104364

In [13]:
# data.head()

In [14]:
# data[data['id']==104041]

In [19]:
data.rename({'nearest_neigbour':'nearest'},axis=1).drop(['Unnamed: 0'], axis=1).to_csv('./with_neigbourghs_V2.csv')

In [17]:
data.rename({'nearest_neigbour':'nearest'},axis=1)

,Unnamed: 0,id,0,1,2,3,4,5,6,7,...,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest
0,0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,-0.799514,...,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,87918
1,0,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,0.797688,...,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,50417
2,0,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,0.699363,...,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,19126
3,0,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,0.854471,...,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,104041
4,0,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,-0.918574,...,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,58133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104359,0,34781,-0.940447,-0.899166,-0.569543,0.123652,0.985020,-0.617012,0.645699,-0.639426,...,-0.986573,-0.284362,0.800393,-0.736587,1.000000e+00,1.982053e-27,0,True,False,66592
104360,0,266,-0.688172,-0.859654,-0.511220,0.020572,0.999849,-0.131492,0.997604,-0.700331,...,-0.948369,0.888818,-0.629098,-0.971198,1.000000e+00,1.320064e-28,0,True,False,17552
104361,0,24627,-0.814291,0.782488,-0.735720,-0.144556,0.999998,-0.180351,0.020851,-0.949530,...,-0.818821,0.714584,-0.810615,-0.679921,8.074531e-06,9.999919e-01,1,True,False,28483
104362,0,18084,0.236926,-0.442427,-0.966645,0.139687,0.999998,-0.368226,-0.881570,-0.743715,...,0.663736,-0.724384,0.928735,-0.758111,1.000000e+00,6.749659e-16,0,True,False,65234
104363,0,6879,0.491427,-0.866658,-0.661957,0.016605,0.988620,0.601567,-0.938614,0.929808,...,-0.393736,0.956509,-0.227563,-0.541957,1.000000e+00,2.930369e-19,0,True,False,22273

In [ ]:
data['nearest_neigbour'].value_counts().to_frame().style.bar()

In [ ]:
data['nearest_neigbour'].value_counts()

In [5]:
data_all = pd.read_csv('./with_neigbourghs.csv')

In [6]:
data_all.head()

,Unnamed: 0,Unnamed: 0.1,id,0,1,2,3,4,5,6,...,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest_neigbour
0,0,0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,...,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,"9897 87918\nName: id, dtype: int64"
1,1,0,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,...,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,"23684 23527\nName: id, dtype: int64"
2,2,0,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,...,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,"30555 98321\nName: id, dtype: int64"
3,3,0,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,...,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,"36801 104041\nName: id, dtype: int64"
4,4,0,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,...,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,"23684 23527\nName: id, dtype: int64"

In [12]:
data_all['nearest_neigbour'][0].split('    ')[1].split('\n')[0]

['87918', 'Name: id, dtype: int64']

In [13]:
data_all['nearest_neigbou_1'] = data_all['nearest_neigbour']

In [14]:
data_all['nearest_neigbou_2'] = data_all['nearest_neigbour']

In [17]:
for i in range(len(data_all['nearest_neigbour'])):
    data_all['nearest_neigbou_1'][i] = data_all['nearest_neigbour'][i].split('    ')[0]
    data_all['nearest_neigbou_2'][i] = data_all['nearest_neigbour'][i].split('    ')[1].split('\n')[0]

/home/alexis/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/alexis/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
data_all.head()

,Unnamed: 0,Unnamed: 0.1,id,0,1,2,3,4,5,6,...,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest_neigbour,nearest_neigbou_1,nearest_neigbou_2
0,0,0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,...,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,"9897 87918\nName: id, dtype: int64",9897,87918
1,1,0,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,...,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,"23684 23527\nName: id, dtype: int64",23684,23527
2,2,0,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,...,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,"30555 98321\nName: id, dtype: int64",30555,98321
3,3,0,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,...,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,"36801 104041\nName: id, dtype: int64",36801,104041
4,4,0,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,...,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,"23684 23527\nName: id, dtype: int64",23684,23527

In [20]:
data_all[data_all['id']==23527]['class']

23684    1
Name: class, dtype: int64

In [25]:
data_all = data_all.drop(['nearest_neigbour'], axis=1)

In [27]:
data_all.rename()

,Unnamed: 0,Unnamed: 0.1,id,0,1,2,3,4,5,6,...,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest_neigbou_2
0,0,0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,...,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,87918
1,1,0,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,...,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,23527
2,2,0,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,...,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,98321
3,3,0,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,...,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,104041
4,4,0,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,...,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,23527

In [28]:
data_all = data_all.rename(columns={"nearest_neigbou_2": "nearest"})

In [31]:
data_all.head()

,id,0,1,2,3,4,5,6,7,8,...,1020,1021,1022,1023,pred_class_0,pred_class_1,class,good_predict,frontier,nearest
0,31239,0.253644,-0.321084,-0.589449,-0.970542,0.998823,0.319632,0.981234,-0.799514,-0.240576,...,-0.980479,-0.429701,-0.525760,-0.922458,1.000000e+00,1.740372e-25,0,True,False,87918
1,49277,-0.569401,-0.987312,-0.599012,-0.194117,0.999915,0.700822,-0.892934,0.797688,0.506043,...,-0.999913,-0.986968,0.289179,-0.564293,1.000000e+00,8.848381e-27,0,True,False,23527
2,1942,-0.099620,-0.986444,-0.361907,0.040220,0.960831,0.166444,0.993530,0.699363,-0.028185,...,-0.997743,-0.902522,0.806135,-0.645377,1.000000e+00,2.634413e-26,0,True,False,98321
3,20118,0.808946,-0.716721,-0.590019,-0.362874,0.999995,0.036835,0.978763,0.854471,-0.250788,...,0.038868,-0.910976,-0.989469,-0.224594,1.077525e-11,1.000000e+00,1,True,False,104041
4,60344,-0.784158,-0.942368,-0.527780,-0.306043,-0.835234,0.623065,0.975667,-0.918574,0.009565,...,-0.832971,-0.108069,0.206828,-0.823972,1.000000e+00,4.594579e-27,0,True,False,23527

In [30]:
data_all = data_all.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)

In [32]:
data_all.to_csv('./with_neigbourghs.csv')